### ISSUE TITLE
Fix the font on the screen - split the difference 

### ISSUE THREAD

**Issue by komalashrafsyed** [SwapUp-dApp/Front-End-v2#49]
![image](https://github.com/user-attachments/assets/f2861088-4386-48e9-8558-a01c5a8c7a80)
![image](https://github.com/user-attachments/assets/d50abb67-4022-48e9-b184-7006acc52a30)

**Comment by KhalilAlliedC** [comment]
Fixed this issue in the following commit 
ff21656d62a024d3e4aba92bc2494a6d4e2b693d
